echo " Clean your phone "
pm uninstall -k --user 0 com.zhihu.android
pm uninstall -k --user 0 com.xiaomi.jr 
pm uninstall -k --user 0 com.ss.android.article.news
pm uninstall -k --user 0 com.taobao.taobao
pm uninstall -k --user 0 com.duokan.free
pm uninstall -k --user 0 com.dragon.read
pm uninstall -k --user 0 com.eg.android.AlipayGphone
pm uninstall -k --user 0 com.xiaomi.youpin
pm uninstall -k --user 0 com.xiaomi.vipaccount
pm uninstall -k --user 0 com.miui.miservice
pm uninstall -k --user 0 com.xiaomi.smarthome
pm uninstall -k --user 0 com.mipay.wallet
pm uninstall -k --user 0 com.xiaomi.gamecenter
pm uninstall -k --user 0 com.xiaomi.shop
pm uninstall -k --user 0 com.miui.voiceassist
pm uninstall -k --user 0 com.android.email
pm uninstall -k --user 0 com.miui.huanji
pm uninstall -k --user 0 com.miui.virtualsim
pm uninstall -k --user 0 com.mi.health
pm uninstall -k --user 0 com.android.browser
echo "done"
